package com.ncubo.chatbot.partesDeLaConversacion;

public class IntencionesNoReferenciadas {

	// Intenciones
		private String INTENCION_FUERA_DE_CONTEXTO = "";
		private String INTENCION_NO_ENTIENDO = "";
		private String INTENCION_DESPEDIDA = "";
		private String INTENCION_SALUDAR = "";
		private String INTENCION_DESPISTADOR = "";
		private String INTENCION_REPETIR_ULTIMA_FRASE = "";
		private String INTENCION_ERROR_CON_WATSON = "";
		private String INTENCION_AGRADECIMIENTO = "";
		private String INTENCION_QUE_PUEDEN_PREGUNTAR = "";
		private String INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = "";
		
		private String[] FRASES_INTENCION_SALUDAR = new String[]{};
		private String[] FRASES_INTENCION_DESPEDIDA = new String[]{};
		private String[] FRASES_INTENCION_FUERA_DE_CONTEXTO  = new String[]{};
		private String[] FRASES_INTENCION_DESPISTADOR = new String[]{};
		private String[] FRASES_INTENCION_REPETIR = new String[]{};
		private String[] FRASES_INTENCION_NO_ENTIENDO = new String[]{};
		private String[] FRASES_INTENCION_ERROR_CON_WATSON = new String[]{};
		private String[] FRASES_INTENCION_AGRADECIMIENTO = new String[]{};
		private String[] FRASES_INTENCION_QUE_PUEDEN_PREGUNTAR = new String[]{};
		private String[] FRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = new String[]{};
		private String[] FRASES_INTENCION_RECORDAR_TEMAS = new String[]{};
		
		
		public IntencionesNoReferenciadas(String fuera_de_contexto, String[] frases_fuera_de_contexto,
				String no_entiendo, String[] frases_no_entiendo, String despedida, String[] frases_despedida,
				String saludar, String[] frases_saludar, String despistador, String[] frases_despistador,
				String repetir, String[] frases_repetir, String error, String[] frases_error,
				String agradecimiento, String[] frases_agradecimiento,
				String que_preguntar, String[] frases_que_preguntar, String otra_consulta, String[] frases_otra_consulta){
			this.INTENCION_AGRADECIMIENTO = agradecimiento;
			this.FRASES_INTENCION_AGRADECIMIENTO = frases_agradecimiento;
			this.INTENCION_DESPEDIDA = despedida;
			this.FRASES_INTENCION_DESPEDIDA = frases_despedida;
			this.INTENCION_DESPISTADOR = despistador;
			this.FRASES_INTENCION_DESPISTADOR = frases_despistador;
			this.INTENCION_ERROR_CON_WATSON = error;
			this.FRASES_INTENCION_ERROR_CON_WATSON = frases_error;
			this.INTENCION_FUERA_DE_CONTEXTO = fuera_de_contexto;
			this.FRASES_INTENCION_FUERA_DE_CONTEXTO = frases_fuera_de_contexto;
			this.INTENCION_NO_ENTIENDO = no_entiendo;
			this.FRASES_INTENCION_NO_ENTIENDO = frases_no_entiendo;
			this.INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = otra_consulta;
			this.FRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = frases_otra_consulta;
			this.INTENCION_QUE_PUEDEN_PREGUNTAR = que_preguntar;
			this.FRASES_INTENCION_QUE_PUEDEN_PREGUNTAR = frases_que_preguntar;
			this.INTENCION_REPETIR_ULTIMA_FRASE = repetir;
			this.FRASES_INTENCION_REPETIR = frases_repetir;
			this.INTENCION_SALUDAR = saludar;
			this.FRASES_INTENCION_SALUDAR = frases_saludar;

		
		}


		public IntencionesNoReferenciadas(){
			
		}
		public String getINTENCION_FUERA_DE_CONTEXTO() {
			return INTENCION_FUERA_DE_CONTEXTO;
		}


		public void setINTENCION_FUERA_DE_CONTEXTO(String iNTENCION_FUERA_DE_CONTEXTO) {
			INTENCION_FUERA_DE_CONTEXTO = iNTENCION_FUERA_DE_CONTEXTO;
		}


		public String getINTENCION_NO_ENTIENDO() {
			return INTENCION_NO_ENTIENDO;
		}


		public void setINTENCION_NO_ENTIENDO(String iNTENCION_NO_ENTIENDO) {
			INTENCION_NO_ENTIENDO = iNTENCION_NO_ENTIENDO;
		}


		public String getINTENCION_DESPEDIDA() {
			return INTENCION_DESPEDIDA;
		}


		public void setINTENCION_DESPEDIDA(String iNTENCION_DESPEDIDA) {
			INTENCION_DESPEDIDA = iNTENCION_DESPEDIDA;
		}


		public String getINTENCION_SALUDAR() {
			return INTENCION_SALUDAR;
		}


		public void setINTENCION_SALUDAR(String iNTENCION_SALUDAR) {
			INTENCION_SALUDAR = iNTENCION_SALUDAR;
		}


		public String getINTENCION_DESPISTADOR() {
			return INTENCION_DESPISTADOR;
		}


		public void setINTENCION_DESPISTADOR(String iNTENCION_DESPISTADOR) {
			INTENCION_DESPISTADOR = iNTENCION_DESPISTADOR;
		}


		public String getINTENCION_REPETIR_ULTIMA_FRASE() {
			return INTENCION_REPETIR_ULTIMA_FRASE;
		}


		public void setINTENCION_REPETIR_ULTIMA_FRASE(String iNTENCION_REPETIR_ULTIMA_FRASE) {
			INTENCION_REPETIR_ULTIMA_FRASE = iNTENCION_REPETIR_ULTIMA_FRASE;
		}


		public String getINTENCION_ERROR_CON_WATSON() {
			return INTENCION_ERROR_CON_WATSON;
		}


		public void setINTENCION_ERROR_CON_WATSON(String iNTENCION_ERROR_CON_WATSON) {
			INTENCION_ERROR_CON_WATSON = iNTENCION_ERROR_CON_WATSON;
		}


		public String getINTENCION_AGRADECIMIENTO() {
			return INTENCION_AGRADECIMIENTO;
		}


		public void setINTENCION_AGRADECIMIENTO(String iNTENCION_AGRADECIMIENTO) {
			INTENCION_AGRADECIMIENTO = iNTENCION_AGRADECIMIENTO;
		}


		public String getINTENCION_QUE_PUEDEN_PREGUNTAR() {
			return INTENCION_QUE_PUEDEN_PREGUNTAR;
		}


		public void setINTENCION_QUE_PUEDEN_PREGUNTAR(String iNTENCION_QUE_PUEDEN_PREGUNTAR) {
			INTENCION_QUE_PUEDEN_PREGUNTAR = iNTENCION_QUE_PUEDEN_PREGUNTAR;
		}


		public String getINTENCION_PREGUNTAR_POR_OTRA_CONSULTA() {
			return INTENCION_PREGUNTAR_POR_OTRA_CONSULTA;
		}


		public void setINTENCION_PREGUNTAR_POR_OTRA_CONSULTA(String iNTENCION_PREGUNTAR_POR_OTRA_CONSULTA) {
			INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = iNTENCION_PREGUNTAR_POR_OTRA_CONSULTA;
		}


		public String[] getFRASES_INTENCION_SALUDAR() {
			return FRASES_INTENCION_SALUDAR;
		}


		public void setFRASES_INTENCION_SALUDAR(String[] fRASES_INTENCION_SALUDAR) {
			FRASES_INTENCION_SALUDAR = fRASES_INTENCION_SALUDAR;
		}


		public String[] getFRASES_INTENCION_DESPEDIDA() {
			return FRASES_INTENCION_DESPEDIDA;
		}


		public void setFRASES_INTENCION_DESPEDIDA(String[] fRASES_INTENCION_DESPEDIDA) {
			FRASES_INTENCION_DESPEDIDA = fRASES_INTENCION_DESPEDIDA;
		}


		public String[] getFRASES_INTENCION_FUERA_DE_CONTEXTO() {
			return FRASES_INTENCION_FUERA_DE_CONTEXTO;
		}


		public void setFRASES_INTENCION_FUERA_DE_CONTEXTO(String[] fRASES_INTENCION_FUERA_DE_CONTEXTO) {
			FRASES_INTENCION_FUERA_DE_CONTEXTO = fRASES_INTENCION_FUERA_DE_CONTEXTO;
		}


		public String[] getFRASES_INTENCION_DESPISTADOR() {
			return FRASES_INTENCION_DESPISTADOR;
		}


		public void setFRASES_INTENCION_DESPISTADOR(String[] fRASES_INTENCION_DESPISTADOR) {
			FRASES_INTENCION_DESPISTADOR = fRASES_INTENCION_DESPISTADOR;
		}


		public String[] getFRASES_INTENCION_REPETIR() {
			return FRASES_INTENCION_REPETIR;
		}


		public void setFRASES_INTENCION_REPETIR(String[] fRASES_INTENCION_REPETIR) {
			FRASES_INTENCION_REPETIR = fRASES_INTENCION_REPETIR;
		}


		public String[] getFRASES_INTENCION_NO_ENTIENDO() {
			return FRASES_INTENCION_NO_ENTIENDO;
		}


		public void setFRASES_INTENCION_NO_ENTIENDO(String[] fRASES_INTENCION_NO_ENTIENDO) {
			FRASES_INTENCION_NO_ENTIENDO = fRASES_INTENCION_NO_ENTIENDO;
		}


		public String[] getFRASES_INTENCION_ERROR_CON_WATSON() {
			return FRASES_INTENCION_ERROR_CON_WATSON;
		}


		public void setFRASES_INTENCION_ERROR_CON_WATSON(String[] fRASES_INTENCION_ERROR_CON_WATSON) {
			FRASES_INTENCION_ERROR_CON_WATSON = fRASES_INTENCION_ERROR_CON_WATSON;
		}


		public String[] getFRASES_INTENCION_AGRADECIMIENTO() {
			return FRASES_INTENCION_AGRADECIMIENTO;
		}


		public void setFRASES_INTENCION_AGRADECIMIENTO(String[] fRASES_INTENCION_AGRADECIMIENTO) {
			FRASES_INTENCION_AGRADECIMIENTO = fRASES_INTENCION_AGRADECIMIENTO;
		}


		public String[] getFRASES_INTENCION_QUE_PUEDEN_PREGUNTAR() {
			return FRASES_INTENCION_QUE_PUEDEN_PREGUNTAR;
		}


		public void setFRASES_INTENCION_QUE_PUEDEN_PREGUNTAR(String[] fRASES_INTENCION_QUE_PUEDEN_PREGUNTAR) {
			FRASES_INTENCION_QUE_PUEDEN_PREGUNTAR = fRASES_INTENCION_QUE_PUEDEN_PREGUNTAR;
		}


		public String[] getFRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA() {
			return FRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA;
		}


		public void setFRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA(
				String[] fRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA) {
			FRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA = fRASES_INTENCION_PREGUNTAR_POR_OTRA_CONSULTA;
		}


		public String[] getFRASES_INTENCION_RECORDAR_TEMAS() {
			return FRASES_INTENCION_RECORDAR_TEMAS;
		}


		public void setFRASES_INTENCION_RECORDAR_TEMAS(String[] fRASES_INTENCION_RECORDAR_TEMAS) {
			FRASES_INTENCION_RECORDAR_TEMAS = fRASES_INTENCION_RECORDAR_TEMAS;
		}
		
}
 